# Generated by Django 5.0.6 on 2024-05-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_compra_fecha_vendedor_compra_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='cantidad',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
