# Generated by Django 5.0.6 on 2024-05-14 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0004_rename_precio_compra_precio_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
