# Generated by Django 5.0.6 on 2024-05-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0005_alter_compra_precio_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='precio_total',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
